---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: pod-resources-checker
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: pod-resources-checker-role
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["apps"]
  resources: ["replicasets", "deployments", "statefulsets", "daemonsets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["batch"]
  resources: ["jobs", "cronjobs"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["metrics.k8s.io"]
  resources: ["pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: pod-resources-checker-binding
subjects:
- kind: ServiceAccount
  name: pod-resources-checker
  namespace: default
roleRef:
  kind: ClusterRole
  name: pod-resources-checker-role
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: batch/v1
kind: Job
metadata:
  name: pod-resources-checker
  namespace: default
spec:
  template:
    spec:
      serviceAccountName: pod-resources-checker
      containers:
      - name: pod-resources-checker
        image: ghcr.io/pratik705/resource-tune/pod-resources:v1
        command: ["python3", "/app/pod_resources.py"]
        #args: ["--namespace", "default"] # Uncomment and specify namespace if needed
      restartPolicy: Never
